### ISSUE TITLE
Unhandled Rejection

### ISSUE THREAD

**Issue by medevs** [kaloraat/react-node-next-multi-user-blogging-platform#6]
×
Unhandled Rejection (TypeError): Cannot read property 'error' of undefined
(anonymous function)
./components/auth/SignupComponent.js:24
  21 |    const user = { name, email, password };
  22 | 
  23 |    signup(user).then(data => {
> 24 |      if (data.error) {
     | ^  25 |          setValues({ ...values, error: data.error, loading: false });
  26 |      } else {
  27 |        setValues({

**Comment by Rach523** [comment]
I am getting the same error. How did you resolve this?

**Comment by ahmed-oublihi** [comment]
i didn't resolve yet

**Comment by medevs** [comment]
go to config.js and replace API

export const API = publicRuntimeConfig.PRODUCTION
    ? publicRuntimeConfig.API_PRODUCTION
    : 'http://localhost:8000/api';

export const APP_NAME = publicRuntimeConfig.APP_NAME;

export const DOMAIN = publicRuntimeConfig.PRODUCTION
    ? publicRuntimeConfig.DOMAIN_PRODUCTION
    : 'http://localhost:8000/';

environment variable doesn't work for some reason so you have to replace the variables with the actual value.

**Comment by sanjkn** [comment]
thank you!

**Comment by Rach523** [comment]
thank you!
