### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by nitink66** [kaloraat/react-node-next-multi-user-blogging-platform#7]
Unable to return the related blogs in the component.
Also tried ```  { JSON.strigify(related) } ```  to debug the error which gives 
{"related":[]}

The ERROR : 

(anonymous function)
./pages/blogs/[slug].js:19   is returning error 

```
17 |    const loadRelated = () => {
  18 |        listRelated({blog}).then(data => {
> 19 |            if (data.error) {
^  20 |                console.log(data.error);
  21 |            } else {
  22 |                setRelated(data);
```

**Comment by kaloraat** [comment]
If you are getting empty array `{"related":[]}` then you have to make sure you are returning related posts from your server. have a look at your controller method that returns related posts:

**Comment by nitink66** [comment]
@kaloraat 
I figured it out It was the issue with the routes, i had a typo
it should have been 
```router.post('/blogs/related',listRelated)```

But now i am getting a whole new error saying 
```related.map is not a function```

I tried debugging using ```{ JSON.stringify(related) }``` which is giving me the response of JSON object.

```
{"related":{"_id":"5eab0a0b2741da18f0d3624e","title":"lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsumlorem ipsum lorem ipsumlorem ipsum lorem ipsumlorem ipsum lorem ipsum  ....","slug":"lorem-blog-3-one",
"postedBy":{"_id":"5e9d3833a73b2c0cec9f5e1c","name":"user1","profile":"http://localhost:3000/profile/RxAq9u5Ck"},"updatedAt":"2020-04-30T17:25:31.977Z"}}
```

The function i'm using

```
const showRelatedBlogs = () => {
        return related.map((blog, i) => (
            <div className="col-md-4" key={i}>
                <article>
                    <RelatedCard blog={blog} />
                </article>
            </div> 

        ));
    };
```

**Comment by nitink66** [comment]
The issue was a typo in backend ,
figured it out.
Had typed  ```Blog.findOne```  instead of  ``` Blog.find```
