### ISSUE TITLE
Unable to get username from isAuth()

### ISSUE THREAD

**Issue by nitink66** [kaloraat/react-node-next-multi-user-blogging-platform#8]
To list all blogs created by the specific user, ```isAuth()``` from actions returns undefined value if it is used as ```const username = isAuth() && isAuth().username ``` .
The backend controller method is working perfectly fine, tried passing the user Id by manually typing it into the code and it works.
[Repo Code](https://github.com/kaloraat/react-node-next-multi-user-blogging-platform/blob/master/104%20auth%20user%20can%20update%20delete%20blog%20frontend/frontend/pages/user/crud/blogs.js)
So it is not getting the value from LocalStorage

**Comment by kaloraat** [comment]
Try deleting local storage manually and start over. Make sure user is available in local storage after signin.

**Comment by nitink66** [comment]
> Try deleting local storage manually and start over. Make sure user is available in local storage after signin.

Tried by deleting the local storage manually and signed in and made sure user exist in localStorage, still returns undefined

**Comment by kaloraat** [comment]
Try `JSON.stringify(isAuth())` and see what you get

**Comment by nitink66** [comment]
> Try `JSON.stringify(isAuth())` and see what you get

This is what ```JSON.stringify(isAuth())``` returns 

```
{"_id":"5ece659149421c1f18c0c756","username":"2asjvwxkq","name":"test3","email":"test3@gmail.com","role":0}
```

**Comment by kaloraat** [comment]
So there is username, you should have no problem using that.
Try ternery operator or use useEffect whenever needed
`isAuth() ? isAuth().username : ''`

**Comment by nitink66** [comment]
> So there is username, you should have no problem using that.
> Try ternery operator or use useEffect whenever needed
> `isAuth() ? isAuth().username : ''`

It worked, getting the username, but is throwing a new error in backend 
```
Cannot read property '_id' of null
```
Also doesn't show all blogs for admin too.
[Repo code](https://github.com/kaloraat/react-node-next-multi-user-blogging-platform/blob/master/104%20auth%20user%20can%20update%20delete%20blog%20frontend/backend/controllers/blog.js)

**Comment by nitink66** [comment]
This issue was, instead of sending the username from page[ blogs.js](https://github.com/kaloraat/react-node-next-multi-user-blogging-platform/blob/master/104%20auth%20user%20can%20update%20delete%20blog%20frontend/frontend/pages/user/crud/blogs.js) and sending it as a prop 
I tried ```const username = isAuth() ? isAuth().username : ' ' ```  inside  [BlogRead.js](https://github.com/kaloraat/react-node-next-multi-user-blogging-platform/blob/master/104%20auth%20user%20can%20update%20delete%20blog%20frontend/frontend/components/crud/BlogRead.js) Component and updated the [BlogRead.js](https://github.com/kaloraat/react-node-next-multi-user-blogging-platform/blob/master/104%20auth%20user%20can%20update%20delete%20blog%20frontend/frontend/actions/blog.js) to 
```
if (username !== 'admin_username') {
        listBlogsEndpoint = `${API}/${username}/blogs`;
    } else {
        listBlogsEndpoint = `${API}/blogs`;
    }

```

It Worked
